# Generated by Django 3.2.4 on 2021-07-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheltuiala',
            name='data_inregistrare',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cheltuiala',
            name='valoare',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='incasare',
            name='data_inregistrare',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incasare',
            name='valoare',
            field=models.FloatField(),
        ),
    ]
