# Generated by Django 3.2.4 on 2021-07-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheltuiala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inregistrare', models.CharField(max_length=100)),
                ('valoare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Incasare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inregistrare', models.CharField(max_length=100)),
                ('valoare', models.IntegerField()),
            ],
        ),
    ]
