# Generated by Django 3.2.3 on 2021-05-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('descriere', models.TextField()),
                ('imagine', models.ImageField(upload_to='cursuri/imagini/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
